### ISSUE TITLE
Can't use.  the video or audio link  403 error

### ISSUE THREAD

**Issue by NewMacPro** [Yash-K-B/YoutubeExtractor#12]
for example 
thanks

https://rr1---sn-vgqsknz7.googlevideo.com/videoplayback?expire=1721041043&ei=M6yUZpmpNeSqzN0Pus-XkA4&ip=159.203.44.246&id=o-ALoMVpy2S5nDFEfpxxMdwVdAi0bkMRfagVuytVzAblYM&itag=399&aitags=133%2C134%2C135%2C136%2C137%2C160%2C242%2C243%2C244%2C247%2C248%2C278%2C394%2C395%2C396%2C397%2C398%2C399&source=youtube&requiressl=yes&xpc=EgVo2aDSNQ%3D%3D&mh=lf&mm=31%2C29&mn=sn-vgqsknz7%2Csn-vgqsrnz6&ms=au%2Crdu&mv=m&mvi=1&pl=21&initcwndbps=350000&bui=AXc671JC-uvVze3hP68Yk0yrvqZezkYLjhKVS6Z7lQpr-4EToNVITowAFt2zq-ryCo8EQhHg6RdbAMbV&spc=NO7bARmnvkCzPd5yyHfAhVTXNun4j4jdxSwzxwM0Do5Alai21dFjo3-PL032&vprv=1&svpuc=1&mime=video%2Fmp4&ns=CuSqOi3KoQcxsiIIe1XlsdEQ&rqh=1&gir=yes&clen=22017244&dur=256.839&lmt=1706485310992181&mt=1721019181&fvip=5&keepalive=yes&c=WEB&sefc=1&txp=4537434&ratebypass=yes&n=FXlrose9XneB-L-Vqsb&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cxpc%2Cbui%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cns%2Crqh%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHlkHjAwRgIhAJK3iLiYpE2RQs7q8Q6WZPqJCsAYid9US3h7tL3Kvn_TAiEAygmysALsI9mapSNMvR8B02BO99fe6ui-nsJ-dx852yM%3D&sig=AJfQdSswRAIgIBED8cruWiwauIMK84mW0oAdyFhvHps7GZOkPetL2ZsCIFD5LmhxDC3ObbWRuUTDsOLJBMMirE0yKCu-O0Ot1ozF

**Comment by Dolanpls** [comment]
As you can see in the link, there is an 'expire' parameter that means that the link won't be abailable once the time ends.
You need to use the link before that 'expire' value.

**Comment by sametserpil** [comment]
same here. trying to download instantly but the link gives me 403 error. could you make it work? @NewMacPro

**Comment by Yash-K-B** [comment]
I have observed this issue last week but not get time to fix it.

**Comment by Yash-K-B** [comment]
use extactV2 of extractor. it will work
