### ISSUE TITLE
Null when I try to find a video by id

### ISSUE THREAD

**Issue by Dolanpls** [Yash-K-B/YoutubeExtractor#2]
WhenI I call _extractor.extract("videoId")_, the response is allways null with any video

**Comment by Yash-K-B** [comment]
The function returns null because the thread in which it is called may be interrupted. please check the extract is called for two times. first one is interrupted and the second one returns the result.

**Comment by Dolanpls** [comment]
I tested it again and I don't know why the other day I was getting a null response in every call 😭 
Now its working perfect, thaks and sorry!
