### ISSUE TITLE
Author image url

### ISSUE THREAD

**Issue by EgorSigolaev** [Yash-K-B/YoutubeExtractor#4]
Am i able to get from VideoDetails object author image url? Or library doesnt provide?

**Comment by Yash-K-B** [comment]
I will provide soon

**Comment by Yash-K-B** [comment]
check the latest version 1.1.3 the author thumbnails are in VideoDetails

**Comment by EgorSigolaev** [comment]
> check the latest version 1.1.3 the author thumbnails are in VideoDetails

Thanks!
