### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by EgorSigolaev** [Yash-K-B/YoutubeExtractor#5]
I was trying to get video info, videoId: Hm80HTT25k8.
I am getting error: java.lang.StringIndexOutOfBoundsException: length=0; index=-2
Did youtube change his algorithm?

**Comment by Yash-K-B** [comment]
No, For me it is working .. You can test. Just fork the repository, build and test. 
latest version 1.1.4

**Comment by EgorSigolaev** [comment]
Hm, working now, all is ok
