### ISSUE TITLE
VideoData contains only 2 quality choices.

### ISSUE THREAD

**Issue by EgorSigolaev** [Yash-K-B/YoutubeExtractor#6]
Video data https://www.youtube.com/watch?v=VZkGL8WWPBU (for example) contains only 2 quality, but as you can see in youtube, video has 5 qualities (144p, 240p, 360p, 480p and 720p). Why extractor provides me only 2 variants?
I used kotlin, video list was trying to get using the code below
`val videoDetails = extractor.extract(youtubeVideoId)`
 `val videoList = videoDetails.streamingData.muxedStreamFormats`

Library version: 1.1.5

Is it able to update library and add more quality variants?

**Comment by Yash-K-B** [comment]
YouTube mux audio and video streams at runtime and give other formats . He dont give other format as muxed streams out of the box... If you need then use audio streams and video streams of your choice and merge... It is impossible to give two streams as a single link
