### ISSUE TITLE
Failed to create VMBridge instance

### ISSUE THREAD

**Issue by flickstree** [Yash-K-B/YoutubeExtractor#7]
Release build not working, got the following issue...

Caused by java.lang.IllegalStateException
Failed to create VMBridge instance
org.mozilla.javascript.VMBridge.makeInstance (VMBridge.java:3)

**it resolved by adding following line in proguard. KIndly Add this rule to the Readme file**
-keep class org.mozilla.javascript.** { *; }

**Comment by Yash-K-B** [comment]
Thanks for identifying the issue
