### ISSUE TITLE
Extraction Exception

### ISSUE THREAD

**Issue by amrashraf1992** [Yash-K-B/YoutubeExtractor#9]
com.yash.youtube_extractor.exceptions.ExtractionException: org.mozilla.javascript.EvaluatorException: missing } after function body (script#3229)
11:39:48.546  W  	at com.yash.youtube_extractor.Extractor.extract(Extractor.java:201)

**Comment by amrashraf1992** [comment]
Used Link

**Video ID : ahy5o5nT4oI**

**Comment by Yash-K-B** [comment]
Fixed! Use version 1.2.8
